version: "3.8"

x-shared-db: &shared_db_env
  POSTGRESS_USER: postgres
  POSTGRESS_PASSWORD: postgres
  POSTGRESS_DB: testdb
  POSTGRESS_HOST: db
  POSTGRESS_PORT: 5432

x-shared-kafka: &shared_kafka_env
  BOOTSTRAP_SERVERS: "kafka-181fcb0d-nihlemdammaha-72ee.aivencloud.com:26123"
  #KAFKA_CA: "ca.pem"
  #KAFKA_KEY: "service.key"
  #KAFKA_CERT:  "service.cert"

services:

  appimage_build:
    image: appimage
    command: ['echo', 'build completed']  # any linux command which directly terminates.
    build:
      context: .
      dockerfile: Dockerfile
  
  scheduler:
    image: appimage
    volumes:
        - ./:/app/
    tty: true
    command:
      - scheduler
    ports:
      - "4545:4545"
    environment: *shared_db_env
    networks:
      - my-proxy-net

  consumer:
    image: appimage
    volumes:
        - ./:/app/
    tty: true
    command:
      - consumer
    ports:
      - "4547:4547"
    environment: 
      <<: *shared_db_env
      <<: *shared_kafka_env
    networks:
      - my-proxy-net


  worker:
    image: appimage
    volumes:
        - ./:/app/
    tty: true
    depends_on:
      - "scheduler"
      - "consumer"
    command:
      - worker
    ports:
      - "4546:4546"
    environment: 
      <<: *shared_db_env
      <<: *shared_kafka_env
    networks:
      - my-proxy-net

networks:
  my-proxy-net:
    external:
      name: custom_network
